export { Home } from "../partial/Home"
export { Header } from "../partial/Header-Footer/Header"
export { Footer } from "../partial/Header-Footer/Footer"
export { Layout } from "../layout/Layout"
export { Contactme } from "../partial/Contactme"